config/routes.rb
Rails.application.routes.draw do
  get 'schedules/index', to:'schedules#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :schedules
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validates :title, :start_date, :end_date, presence:true
  validates :title, length: {maximum:20}
  validate :date_check
  validates :memo, length: {maximum:500}

  private

  def date_check
    if end_date < start_date
      errors.add(:end_date, "終了日は開始日以降の日付で選択してください。")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.all
    @date = Time.zone.today
  end
  
  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(params.require(:schedule).permit(:title, :start_date, :end_date, :all_day_check, :memo))
    if @schedule.save
      flash[:notice] = "スケジュールを登録しました"
      redirect_to :schedules
    else
      render "new"
    end
  end

  def show
    @schedule = Schedule.find(params[:id])
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(params.require(:schedule).permit(:title, :start_date, :end_date, :all_day_check, :memo))
      flash[:notice] = "スケジュールを更新しました"
      redirect_to :schedules
    else
      render "edit"
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    flash[:notice] = "スケジュールを削除しました"
    redirect_to :schedules
  end

end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduleManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h3>スケジュール管理アプリ</h3>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/schedules/edit.html.erb
<div class="show-edit-new_width">
  <h3>予定を編集してください</h3>

  <%= form_with model:@schedule do |f| %>
    <div class="edit_elements">
      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title, class:"title_field"%>
    </div>

    <div class="edit-new_elements">
      <%= f.label :start, "開始日" %>
      <%= f.date_select :start %>
    </div>

    <div class="edit-new_elements">
    <%= f.label :end, "終了日" %>
    <%= f.date_select :end %>
    </div>

    <div class="edit-new_elements"> 
      <%= f.check_box :all_day_check, {}, '○', '' %>
      <%= f.label :all_day_check, "終日の場合はチェックを入れます" %>
    </div>

    <div class="edit-new_elements">
      <%= f.label :memo, "スケジュールメモ" %>
      <%= f.text_area :memo, class:"memo_area" %>
    </div>

    <div class="edit-new_elements">
      <button><%= link_to "キャンセル", :schedules, class:"link" %></button>
      <%= f.submit "保存" %>
    </div>
    
  <% end %>
</div>

app/views/schedules/index.html.erb
<div class="whole_width">
  <div class="contents_header">
    <h3>予定一覧</h3>
    <%= link_to "新規登録", :new_schedule, class:"link blue_button" %>
  </div>

  <table>
    <thead>
      <tr>
        <th>id</th>
        <th>タイトル</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>終日</th>
        <th>更新日時</th>
      </tr>
    </thead>
    <tbody>
      <% @schedules.each do |schedule| %>
        <tr>
          <td><%= schedule.id %></td>
          <td><%= schedule.title %></td>
          <td><%= schedule.start_date %></td>
          <td><%= schedule.end_date %></td>
          <td><%= schedule.all_day_check %></td>
          <td><%= schedule.updated_at.to_s(:datetime_jp) %></td>
          <td><%= link_to "詳細", schedule, class:"link" %></td>
          <td><%= link_to "編集", [:edit, schedule], class:"link" %></td>
          <td><%= link_to "削除", schedule, method: :delete, data: { confirm: "予定を削除しますか？" }, class:"link" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="index_footer">
    <p>予定合計 <%= Schedule.count %> 件</p>
    <p>本日の日付 <%= @date %></p>
  </div>
</div>

<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>

app/views/schedules/new.html.erb
<div class="show-edit-new_width">
  <h3>予定の新規追加</h3>

  <%= render "shared/error", obj:@schedule %>

  <%= form_with model:@schedule do |f| %>
    <div class="edit-new_elements">
      <%= f.label :title, "タイトル" %>
      <%= f.text_field :title, class:"title_field" %>
    </div>

    <div class="edit-new_elements">
      <%= f.label :start, "開始日" %>
      <%= f.date_select :start_date %>
    </div>

    <div class="edit-new_elements">
    <%= f.label :end, "終了日" %>
    <%= f.date_select :end_date %>
    </div>

    <div class="edit-new_elements">
      <%= f.check_box :all_day_check, {}, '○', ''%>
      <%= f.label :all_day_check, "終日の場合はチェックを入れます" %>
    </div>

    <div class="edit-new_elements">
      <%= f.label :memo, "スケジュールメモ" %>
      <%= f.text_area :memo, class:"memo_area" %>
    </div>

    <div class="edit-new_elements">
      <button><%= link_to "キャンセル", :schedules, class:"link" %></button>
      <%= f.submit "保存" %>
    </div>
    
  <% end %>
</div>

app/views/schedules/show.html.erb
<div class="show-edit-new_width">
  <a><%= link_to "← 一覧に戻る", :schedules, class:"link" %></a>
  <div class="contents_header">
    <h2 class="PageTitle"><%= @schedule.title %></h2>
    <%= link_to "編集", edit_schedule_path(@schedule), class:"link blue_button" %>
  </div>

  <div>
    <table>
      <tbody>
        <tr>
          <th>開始日</th>
          <td><%= @schedule.start_date %></td>
        </tr>
        <tr>
          <th>終了日</th>
          <td><%= @schedule.end_date %></td>
        </tr>
        <tr>
          <th>終日</th>
          <td><%= @schedule.all_day_check %></td>
        </tr>
        <tr>
          <th>スケジュールメモ</th>
          <td><%= @schedule.memo %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
<% obj.errors.full_messages.each do |message| %>
  <ul>
    <li><%= message %></li>
  </ul>
<% end %>
<% end %>